### ISSUE TITLE
"Files with Issues" section is empty

### ISSUE THREAD

**Issue by H0R5E** [LintlyCI/Lintly-Issues#11]
Hi Grant,

For some reason sometimes I am not getting any information from the "Files with Issues" section of a build. 

See the following screenshot:

<img width="960" alt="missing_issues" src="https://user-images.githubusercontent.com/5088535/28067080-961df57a-6637-11e7-9ee7-3eb06444b0de.PNG">

Best wishes,

Mat

**Comment by progys** [comment]
Me too.

**Comment by grantmcconnaughey** [comment]
Sorry about that. That came from upgrading from Django 1.9 to 1.11 recently. It will be fixed in the next release.

Thanks for pointing it out!

**Comment by uostim** [comment]
Did this get resolved yet?  Looks like mine is still empty!  Thanks

**Comment by danielsamuels** [comment]
Just wondering if there have been any updates to resolve this issue, we're seeing it on [one of our projects](https://lintly.com/gh/onespacemedia/project-template/) too.

**Comment by grantmcconnaughey** [comment]
Fixed!

Sorry for the delay. I have been porting Lintly to Python 3.6 _and_ switching hosting to AWS Lambda. Note to self: do things like this one at a time.
