### ISSUE TITLE
Does Lintly send PR?

### ISSUE THREAD

**Issue by nepsilon** [LintlyCI/Lintly-Issues#2]
Does Lintly send PRs with the edits to be made to make turn the code base 100% lint'ed?

Does it at each commit? Can it be for a specific tag/branch?

**Comment by grantmcconnaughey** [comment]
Hey there, @nepsilon.

Just to clarify, do you mean does Lintly create its own PRs to fix the issues that it detects? If so, no, Lintly does not do that right now. Instead it lints the project and reports any introduced issues in a PR.

Yes, it does lint at each commit. Currently there is no way to tell Lintly to only lint certain tags or branches, but that would be a great feature. I can add it to my backlog.

Grant

**Comment by nepsilon** [comment]
Yes, I meant sending PR the way https://pyup.io does, after checking for new package version. Code lint'ing can be 100% automated so have a auto-send PR would makes sense and help a lot.

My ideal workflow would be:
I push an release candidate tag (eg: `rc-01`) on github, lintly sees it and send a PR with the changed need for a clean lint'ed code base.

That'd allow me to keep my focus on the dev. Without making lintly a destination for me.

**Comment by grantmcconnaughey** [comment]
Good stuff. Thanks a lot for the feedback. I'll put it on my list.

**Comment by nepsilon** [comment]
Happy to contribute 👍
