### ISSUE TITLE
Private Repos

### ISSUE THREAD

**Issue by afiaka87** [LintlyCI/Lintly-Issues#3]
Not severe - I know you mention that support for private repos is coming soon.  In the meantime I'm just sort of testing snippets with it, but our company can't actually use it on our codebases. 

Does GitHub's api allow _another organization's_ private repos to be accessed? That'd be ideal.

**Comment by grantmcconnaughey** [comment]
Hey there, @claymullis.

Lintly works by storing the API token of each user. That token will have access to any organization's private repos. So in effect Lintly is acting on behalf of a user in an org and can work with their private repos.

I hope that clears things up! Let me know if you have any other questions.
