### ISSUE TITLE
Lintly badge not working?

### ISSUE THREAD

**Issue by audiolion** [LintlyCI/Lintly-Issues#4]
Integrated Lintly with [my new project](https://github.com/audiolion/django-behaviors) and included the rST badge variant into my README.rst but it isn't rendering. Everything looks right with the syntax so I am not sure what is going on.

**Comment by grantmcconnaughey** [comment]
Hey @audiolion! That's pretty odd. 😕 The URL to render the badge seems to be working fine (`https://lintly.com/gh/audiolion/django-behaviors/badge.svg`). It looks like GitHub is doing some sort of caching thing because the URL it's actually hitting is `https://camo.githubusercontent.com/030c71fd1aa788e39d59aa149bcb958e3b1cead5/68747470733a2f2f6c696e746c792e636f6d2f67682f617564696f6c696f6e2f646a616e676f2d6265686176696f72732f62616467652e737667`.

Let me render it here and see if it works: [![Lintly](https://lintly.com/gh/audiolion/django-behaviors/badge.svg)](https://lintly.com/gh/audiolion/django-behaviors/)

**Comment by grantmcconnaughey** [comment]
The URL `https://lintly.com/gh/audiolion/django-behaviors/badge.svg` actually issues a redirect to `https://img.shields.io/badge/lintly-100%-brightgreen.svg`. I wonder if that is causing the caching issue with GitHub. 

Thanks a lot for the heads up. I'll definitely look into this.

**Comment by audiolion** [comment]
👍  yeah I thought it might be the redirect that causes the issue, awesome product keep the great work!

**Comment by grantmcconnaughey** [comment]
Thanks so much! That means a lot.

**Comment by progys** [comment]
Hello, I tried lintly - super easy to setup the project! Noticed that the badge link does not work and wanted to report it.  Good work with the app!

**Comment by grantmcconnaughey** [comment]
Thanks for the heads up, @progys! I'm still trying to figure out why it's happening. The badge does issue a redirect to shields.io, but GitHub camo should follow the redirect. I'm pretty much doing exactly what [ReadTheDocs does](https://github.com/rtfd/readthedocs.org/blob/499a74076f0debae09acc1d4c4eeeab03f8f557e/readthedocs/projects/views/public.py#L109), so I'm not sure why it's not working. 😕

I'll get it figured out, though. Thanks for your patience!

**Comment by H0R5E** [comment]
Same here:

https://github.com/DTOcean/polite

**Comment by H0R5E** [comment]
I had a quick look around and I think this has something to do with the headers being sent from shields.

It looks like camo needs "no-cache" for the Cache-Control header. See [here](https://help.github.com/articles/about-anonymized-image-urls/#an-image-that-changed-recently-is-not-updating).

It seems like shields.io now returns maxAge=86400 for all badges made through the standard API. See badges/shields#726.

**Comment by grantmcconnaughey** [comment]
@H0R5E Thanks a lot for looking into this! I'll give that a shot and see if it improvements.

Thanks for your patience everyone. I've had a few big changes over the last few weeks and haven't been able to work on Lintly much.

**Comment by audiolion** [comment]
I know that feeling @grantmcconnaughey, I am amazed you were able to build the product in your spare time, you are an inspiration

**Comment by grantmcconnaughey** [comment]
I've submitted a ticket to GitHub and am waiting to hear back.

By the way, here are the headers from Lintly/ReadTheDocs. ReadTheDocs badges work fine; Lintly badges do not.

### Lintly

```
grant > curl -i https://lintly.com/gh/grantmcconnaughey/django-avatar/badge.svg
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Content-Type: text/html; charset=utf-8
Date: Mon, 17 Apr 2017 13:02:41 GMT
Expires: Mon, 17 Apr 2017 13:02:41 GMT
Last-Modified: Mon, 17 Apr 2017 13:02:41 GMT
Location: https://img.shields.io/badge/lintly-97%-brightgreen.svg?
Server: Apache/2.4.23 (Amazon) mod_wsgi/3.5 Python/2.7.12
Vary: Cookie,User-Agent
X-Frame-Options: SAMEORIGIN
Content-Length: 0
Connection: keep-alive
```

### ReadTheDocs

```
grant > curl -i https://readthedocs.org/projects/django-avatar/badge/\?version\=latest
HTTP/1.1 302 Found
Server: nginx/1.10.0 (Ubuntu)
Date: Mon, 17 Apr 2017 13:03:38 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Language, Cookie
Location: https://img.shields.io/badge/docs-latest-brightgreen.svg?style=flat
Content-Language: en
Cache-Control: no-cache
X-Frame-Options: DENY
X-Deity: web01
```

**Comment by grantmcconnaughey** [comment]
Fixed! Check it out, a working badge:

[![Lintly](https://lintly.com/gh/grantmcconnaughey/django-avatar/badge.svg)](https://lintly.com/gh/grantmcconnaughey/django-avatar/)

Thanks a lot for reporting this, @audiolion. Always remember to properly encode your URLs, kids.

**Comment by audiolion** [comment]
It was literally the `?` at the end of the URL?

**Comment by grantmcconnaughey** [comment]
It wasn't the initial URL, it was the redirect URL. Specifically the `%` sign in the redirect URL. It should have been URL encoded as `%25`.

So this: `https://img.shields.io/badge/lintly-97%-brightgreen.svg`

Becomes this: `https://img.shields.io/badge/lintly-97%25-brightgreen.svg`

**Comment by audiolion** [comment]
hahahaha that is great 👍

**Comment by H0R5E** [comment]
Thanks for the fix Grant!
