### ISSUE TITLE
Lintly Bot customziation

### ISSUE THREAD

**Issue by vladcalin** [LintlyCI/Lintly-Issues#6]
I am wondering if there is currently any way to configure the Lintly Bot behavior because it is currently spamming all my pull requests with "Line too long" issues.

I a wondering if there is or will be some options to customize the behavior of the Lintly Bot, or maybe instead of commenting once for every found issue, it might post a single comment with a summary of the issues?

Thanks and keep up the good work!

**Comment by grantmcconnaughey** [comment]
Hey @vladcalin. You can customize the checks that Lintly performs by adding a Flake8 configuration file to your repo (that's what Lintly uses under the hood). [Here are the docs], which have a bit more information.
