### ISSUE TITLE
Building has stopped?

### ISSUE THREAD

**Issue by H0R5E** [LintlyCI/Lintly-Issues#8]
Hi,

I don't know if I have done something wrong, but Lintly seems to have stopped building my projects. The last time there seems to have been a build was May 17, but I have created and merged some PRs since then. See, for instance: https://github.com/DTOcean/dtocean-core

Many thanks,

Mat

**Comment by grantmcconnaughey** [comment]
Hey there,

For some reason Lintly stopped picking up new builds. I removed and recreated the Celery Docker containers and it is chugging through the outstanding builds now.

Thanks for bringing this up! I'll keep an eye on it and see if I can figure out why it happened.

Grant

**Comment by H0R5E** [comment]
No, problem. Thanks for sorting it out so quickly!

Mat


*Dr. Mathew Topper*
Lead Computational Scientist

Policy and Innovation Group
Institute for Energy Systems
School of Engineering
The University of Edinburgh
Faraday Building, King's Buildings
Mayfield Road, Edinburgh
EH9 3DW

Email: dataonlygreater@gmail.com
Skype: doctor.topper
Phone: +353 (0)85 166 3178
Web: www.eng.ed.ac.uk
Web: www.policyandinnovationedinburgh.org

The University of Edinburgh is a charitable body, registered in Scotland,
with registration number SC005336.

**Comment by H0R5E** [comment]
I think, perhaps, it has stopped working again. I've got no response from a recent PR:

https://github.com/DTOcean/dtocean-core/pull/15

**Comment by grantmcconnaughey** [comment]
Hey @H0R5E, I will look into this. It looks like Lintly is running builds for your project (https://lintly.com/gh/DTOcean/dtocean-core/). It must be having trouble commenting on the PR. I'll check the logs.

Thanks!

**Comment by grantmcconnaughey** [comment]
You will need to add the `notifications` section to your lintly.yml file.

```
notifications:
  commit_status:
    enabled: true
  pr_comments:
    enabled: true
```

**Comment by H0R5E** [comment]
OK, thanks I will give it a try! Yeah, it wasn't super clear what was required from the docs. My assumption was that if you provided your own lintly.yml file then any defaults you didn't overwrite would be maintained. Might it not be better to update the configuration rather than overwrite it?

**Comment by H0R5E** [comment]
The proposed changes to the config file worked for me. See:

https://github.com/DTOcean/dtocean-core/pull/17

**Comment by H0R5E** [comment]
Hi Grant, it looks like lintly has stopped again. I added and merged a PR yesterday here https://lintly.com/gh/DTOcean/dtocean-core/ but nothing has happened since the 6th.

**Comment by grantmcconnaughey** [comment]
Argggg. I think I'm going to have to switch away from SQS as just use Redis.

Sorry for the delay on all this. I've had a family emergency going on the last few weeks and haven't had time to look into much of anything.
